{
 "title": "Dashboard1",
 "time": { "from": "now-30d", "to": "now" },
 "panels": [
  {
   "title": "Prediction drift",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT prediction_drift FROM churn_metrics LIMIT 50 "
    }
   ]
  },
  {
   "title": "missing values",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT share_missing_values FROM churn_metrics LIMIT 50 "
    }
   ]
  },
  {
   "title": "Drifted columns",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT num_drifted_columns FROM churn_metrics LIMIT 50 "
    }
   ]
  }
 ]
}